/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package currencyconvertor;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class NewJFrame2 extends javax.swing.JFrame {

    /** Creates new form NewJFrame2 */
    public NewJFrame2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(222, 47, 62));
        setForeground(new java.awt.Color(255, 196, 241));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jLabel9.setText("CURRENCY CONVERTOR");
        jPanel1.add(jLabel9);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 900;
        gridBagConstraints.ipady = 62;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.ipady = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 0);
        getContentPane().add(jPanel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.ipady = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 0, 0);
        getContentPane().add(jPanel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.ipady = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 0);
        getContentPane().add(jPanel5, gridBagConstraints);

        jPanel7.setBackground(new java.awt.Color(230, 6, 6));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jButton2.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jButton2.setText("RESET");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 102;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 668, 0, 0);
        jPanel7.add(jButton2, gridBagConstraints);

        jButton3.setBackground(new java.awt.Color(246, 181, 175));
        jButton3.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jButton3.setText("LIST OF WORLD CURRENCIES");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = -13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(56, 103, 0, 35);
        jPanel7.add(jButton3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 0, 0, 0);
        getContentPane().add(jPanel7, gridBagConstraints);

        jComboBox2.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AED", "AUD", "BDT", "BHD", "CAD", "CNY", "EGP", "EUR", "IDR", "INR", "JPY", "KWD", "LKR", "MYR", "OMR", "PKR", "RUB", "THB", "USD" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(255, 51, 51)));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 155;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 142, 0, 0);
        getContentPane().add(jComboBox2, gridBagConstraints);

        jComboBox1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AED", "AUD", "BDT", "BHD", "CAD", "CNY", "EGP", "EUR", "IDR", "INR", "JPY", "KWD", "LKR", "MYR", "OMR", "PKR", "RUB", "THB", "USD" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(255, 51, 51)));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 155;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 3, 0, 0);
        getContentPane().add(jComboBox1, gridBagConstraints);

        jTextField1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(255, 51, 51)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 328;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(67, 3, 0, 0);
        getContentPane().add(jTextField1, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 326;
        gridBagConstraints.ipady = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(67, 142, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        jButton1.setText("CONVERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(118, 84, 0, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel1.setText(null);
        jTextField1.setText(null);
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Double amm= Double.parseDouble(jTextField1.getText());
        if(jComboBox1.getSelectedItem().toString()=="AED" & jComboBox2.getSelectedItem().toString()=="AED"){
            String convert= String.format("%.2f", amm);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AED" & jComboBox2.getSelectedItem().toString()=="AUD"){

            String convert= String.format("%.2f", amm*0.36);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AED" & jComboBox2.getSelectedItem().toString()=="BDT"){

            String convert= String.format("%.2f", amm*23.07);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AED" & jComboBox2.getSelectedItem().toString()=="BHD"){

            String convert= String.format("%.2f", amm*0.10);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AED" & jComboBox2.getSelectedItem().toString()=="CAD"){

            String convert= String.format("%.2f", amm*0.34);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AED" & jComboBox2.getSelectedItem().toString()=="CNY"){

            String convert= String.format("%.2f", amm*1.78);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AED" & jComboBox2.getSelectedItem().toString()=="EGP"){

            String convert= String.format("%.2f", amm*4.28);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AED" & jComboBox2.getSelectedItem().toString()=="EUR"){

            String convert= String.format("%.2f", amm*0.23);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AED" & jComboBox2.getSelectedItem().toString()=="IDR"){

            String convert= String.format("%.2f", amm*3931.41);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AED" & jComboBox2.getSelectedItem().toString()=="INR"){

            String convert= String.format("%.2f", amm*19.78);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AED" & jComboBox2.getSelectedItem().toString()=="JPY"){

            String convert= String.format("%.2f", amm*29.71);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AED" & jComboBox2.getSelectedItem().toString()=="KWD"){

            String convert= String.format("%.2f", amm*0.082);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AED" & jComboBox2.getSelectedItem().toString()=="LKR"){

            String convert= String.format("%.2f", amm*54.03);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AED" & jComboBox2.getSelectedItem().toString()=="MYR"){

            String convert= String.format("%.2f", amm*1.13);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AED" & jComboBox2.getSelectedItem().toString()=="OMR"){

            String convert= String.format("%.2f", amm*0.10);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AED" & jComboBox2.getSelectedItem().toString()=="PKR"){

            String convert= String.format("%.2f", amm*42.16);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="AED" & jComboBox2.getSelectedItem().toString()=="RUB"){

            String convert= String.format("%.2f", amm*20.77);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="AED" & jComboBox2.getSelectedItem().toString()=="THB"){

            String convert= String.format("%.2f", amm*8.48);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="AED" & jComboBox2.getSelectedItem().toString()=="USD"){

            String convert= String.format("%.2f", amm*0.27);
            jLabel1.setText(convert);
        }
        //AED IS CLOSED
        else if(jComboBox1.getSelectedItem().toString()=="AUD" & jComboBox2.getSelectedItem().toString()=="AED"){
            String convert= String.format("%.2f", amm*2.79);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AUD" & jComboBox2.getSelectedItem().toString()=="AUD"){

            String convert= String.format("%.2f", amm);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AUD" & jComboBox2.getSelectedItem().toString()=="BDT"){

            String convert= String.format("%.2f", amm*23.07*2.79);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AUD" & jComboBox2.getSelectedItem().toString()=="BHD"){

            String convert= String.format("%.2f", amm*0.10*2.79);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AUD" & jComboBox2.getSelectedItem().toString()=="CAD"){

            String convert= String.format("%.2f", amm*0.34*2.79);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AUD" & jComboBox2.getSelectedItem().toString()=="CNY"){

            String convert= String.format("%.2f", amm*1.78*2.79);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AUD" & jComboBox2.getSelectedItem().toString()=="EGP"){

            String convert= String.format("%.2f", amm*4.28*2.79);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AUD" & jComboBox2.getSelectedItem().toString()=="EUR"){

            String convert= String.format("%.2f", amm*0.23*2.79);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AUD" & jComboBox2.getSelectedItem().toString()=="IDR"){

            String convert= String.format("%.2f", amm*3931.41*2.79);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AUD" & jComboBox2.getSelectedItem().toString()=="INR"){

            String convert= String.format("%.2f", amm*19.78*2.79);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AUD" & jComboBox2.getSelectedItem().toString()=="JPY"){

            String convert= String.format("%.2f", amm*29.71*2.79);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AUD" & jComboBox2.getSelectedItem().toString()=="KWD"){

            String convert= String.format("%.2f", amm*0.082*2.79);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AUD" & jComboBox2.getSelectedItem().toString()=="LKR"){

            String convert= String.format("%.2f", amm*54.03*2.79);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AUD" & jComboBox2.getSelectedItem().toString()=="MYR"){

            String convert= String.format("%.2f", amm*1.13*2.79);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AUD" & jComboBox2.getSelectedItem().toString()=="OMR"){

            String convert= String.format("%.2f", amm*0.10*2.79);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="AUD" & jComboBox2.getSelectedItem().toString()=="PKR"){

            String convert= String.format("%.2f", amm*42.16*2.79);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="AUD" & jComboBox2.getSelectedItem().toString()=="RUB"){

            String convert= String.format("%.2f", amm*20.77*2.79);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="AUD" & jComboBox2.getSelectedItem().toString()=="THB"){

            String convert= String.format("%.2f", amm*8.48*2.79);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="AUD" & jComboBox2.getSelectedItem().toString()=="USD"){

            String convert= String.format("%.2f", amm*0.27*2.79);
            jLabel1.setText(convert);
        }
        //AUD closed
        else if(jComboBox1.getSelectedItem().toString()=="BDT" & jComboBox2.getSelectedItem().toString()=="AED"){
            String convert= String.format("%.2f", amm*0.043);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BDT" & jComboBox2.getSelectedItem().toString()=="AUD"){

            String convert= String.format("%.2f", amm*0.36*0.043);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BDT" & jComboBox2.getSelectedItem().toString()=="BDT"){

            String convert= String.format("%.2f", amm);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BDT" & jComboBox2.getSelectedItem().toString()=="BHD"){

            String convert= String.format("%.2f", amm*0.10*0.043);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BDT" & jComboBox2.getSelectedItem().toString()=="CAD"){

            String convert= String.format("%.2f", amm*0.34*0.043);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BDT" & jComboBox2.getSelectedItem().toString()=="CNY"){

            String convert= String.format("%.2f", amm*1.78*0.043);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BDT" & jComboBox2.getSelectedItem().toString()=="EGP"){

            String convert= String.format("%.2f", amm*4.28*0.043);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BDT" & jComboBox2.getSelectedItem().toString()=="EUR"){

            String convert= String.format("%.2f", amm*0.23*0.043);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BDT" & jComboBox2.getSelectedItem().toString()=="IDR"){

            String convert= String.format("%.2f", amm*3931.41*0.043);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BDT" & jComboBox2.getSelectedItem().toString()=="INR"){

            String convert= String.format("%.2f", amm*19.78*0.043);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BDT" & jComboBox2.getSelectedItem().toString()=="JPY"){

            String convert= String.format("%.2f", amm*29.71*0.043);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BDT" & jComboBox2.getSelectedItem().toString()=="KWD"){

            String convert= String.format("%.2f", amm*0.082*0.043);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BDT" & jComboBox2.getSelectedItem().toString()=="LKR"){

            String convert= String.format("%.2f", amm*54.03*0.043);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BDT" & jComboBox2.getSelectedItem().toString()=="MYR"){

            String convert= String.format("%.2f", amm*1.13*0.043);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BDT" & jComboBox2.getSelectedItem().toString()=="OMR"){

            String convert= String.format("%.2f", amm*0.10*0.043);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BDT" & jComboBox2.getSelectedItem().toString()=="PKR"){

            String convert= String.format("%.2f", amm*42.16*0.043);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="BDT" & jComboBox2.getSelectedItem().toString()=="RUB"){

            String convert= String.format("%.2f", amm*20.77*0.043);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="BDT" & jComboBox2.getSelectedItem().toString()=="THB"){

            String convert= String.format("%.2f", amm*8.48*0.043);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="BDT" & jComboBox2.getSelectedItem().toString()=="USD"){

            String convert= String.format("%.2f", amm*0.27*0.043);
            jLabel1.setText(convert);
        }
        //BDT is closed
        else if(jComboBox1.getSelectedItem().toString()=="BHD" & jComboBox2.getSelectedItem().toString()=="AED"){
            String convert= String.format("%.2f", amm*9.75);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BHD" & jComboBox2.getSelectedItem().toString()=="AUD"){

            String convert= String.format("%.2f", amm*0.36*9.75);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BHD" & jComboBox2.getSelectedItem().toString()=="BDT"){

            String convert= String.format("%.2f", amm*23.07*9.75);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BHD" & jComboBox2.getSelectedItem().toString()=="BHD"){

            String convert= String.format("%.2f", amm);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BHD" & jComboBox2.getSelectedItem().toString()=="CAD"){

            String convert= String.format("%.2f", amm*0.34*9.75);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BHD" & jComboBox2.getSelectedItem().toString()=="CNY"){

            String convert= String.format("%.2f", amm*1.78*9.75);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BHD" & jComboBox2.getSelectedItem().toString()=="EGP"){

            String convert= String.format("%.2f", amm*4.28*9.75);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BHD" & jComboBox2.getSelectedItem().toString()=="EUR"){

            String convert= String.format("%.2f", amm*0.23*9.75);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BHD" & jComboBox2.getSelectedItem().toString()=="IDR"){

            String convert= String.format("%.2f", amm*3931.41*9.75);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BHD" & jComboBox2.getSelectedItem().toString()=="INR"){

            String convert= String.format("%.2f", amm*19.78*9.75);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BHD" & jComboBox2.getSelectedItem().toString()=="JPY"){

            String convert= String.format("%.2f", amm*29.71*9.75);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BHD" & jComboBox2.getSelectedItem().toString()=="KWD"){

            String convert= String.format("%.2f", amm*0.082*9.75);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BHD" & jComboBox2.getSelectedItem().toString()=="LKR"){

            String convert= String.format("%.2f", amm*54.03*9.75);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BHD" & jComboBox2.getSelectedItem().toString()=="MYR"){

            String convert= String.format("%.2f", amm*1.13*9.75);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BHD" & jComboBox2.getSelectedItem().toString()=="OMR"){

            String convert= String.format("%.2f", amm*0.10*9.75);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="BHD" & jComboBox2.getSelectedItem().toString()=="PKR"){

            String convert= String.format("%.2f", amm*42.16*9.75);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="BHD" & jComboBox2.getSelectedItem().toString()=="RUB"){

            String convert= String.format("%.2f", amm*20.77*9.75);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="BHD" & jComboBox2.getSelectedItem().toString()=="THB"){

            String convert= String.format("%.2f", amm*8.48*9.75);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="BHD" & jComboBox2.getSelectedItem().toString()=="USD"){

            String convert= String.format("%.2f", amm*0.27*9.75);
            jLabel1.setText(convert);
        }
//BHD is closed
           else if(jComboBox1.getSelectedItem().toString()=="CAD" & jComboBox2.getSelectedItem().toString()=="AED"){
            String convert= String.format("%.2f", amm*2.91);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CAD" & jComboBox2.getSelectedItem().toString()=="AUD"){

            String convert= String.format("%.2f", amm*0.36*2.91);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CAD" & jComboBox2.getSelectedItem().toString()=="BDT"){

            String convert= String.format("%.2f", amm*23.07*2.91);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CAD" & jComboBox2.getSelectedItem().toString()=="BHD"){

            String convert= String.format("%.2f", amm*0.10*2.91);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CAD" & jComboBox2.getSelectedItem().toString()=="CAD"){

            String convert= String.format("%.2f", amm);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CAD" & jComboBox2.getSelectedItem().toString()=="CNY"){

            String convert= String.format("%.2f", amm*1.78*2.91);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CAD" & jComboBox2.getSelectedItem().toString()=="EGP"){

            String convert= String.format("%.2f", amm*4.28*2.91);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CAD" & jComboBox2.getSelectedItem().toString()=="EUR"){

            String convert= String.format("%.2f", amm*0.23*2.91);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CAD" & jComboBox2.getSelectedItem().toString()=="IDR"){

            String convert= String.format("%.2f", amm*3931.41*2.91);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CAD" & jComboBox2.getSelectedItem().toString()=="INR"){

            String convert= String.format("%.2f", amm*19.78*2.91);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CAD" & jComboBox2.getSelectedItem().toString()=="JPY"){

            String convert= String.format("%.2f", amm*29.71*2.91);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CAD" & jComboBox2.getSelectedItem().toString()=="KWD"){

            String convert= String.format("%.2f", amm*0.082*2.91);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CAD" & jComboBox2.getSelectedItem().toString()=="LKR"){

            String convert= String.format("%.2f", amm*54.03*2.91);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CAD" & jComboBox2.getSelectedItem().toString()=="MYR"){

            String convert= String.format("%.2f", amm*1.13*2.91);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CAD" & jComboBox2.getSelectedItem().toString()=="OMR"){

            String convert= String.format("%.2f", amm*0.10*2.91);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CAD" & jComboBox2.getSelectedItem().toString()=="PKR"){

            String convert= String.format("%.2f", amm*42.16*2.91);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="CAD" & jComboBox2.getSelectedItem().toString()=="RUB"){

            String convert= String.format("%.2f", amm*20.77*2.91);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="CAD" & jComboBox2.getSelectedItem().toString()=="THB"){

            String convert= String.format("%.2f", amm*8.48*2.91);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="CAD" & jComboBox2.getSelectedItem().toString()=="USD"){

            String convert= String.format("%.2f", amm*0.27*2.91);
            jLabel1.setText(convert);
        }
//CAD is closed
        else if(jComboBox1.getSelectedItem().toString()=="CNY" & jComboBox2.getSelectedItem().toString()=="AED"){
            String convert= String.format("%.2f", amm*0.56);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CNY" & jComboBox2.getSelectedItem().toString()=="AUD"){

            String convert= String.format("%.2f", amm*0.36*0.56);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CNY" & jComboBox2.getSelectedItem().toString()=="BDT"){

            String convert= String.format("%.2f", amm*23.07*0.56);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CNY" & jComboBox2.getSelectedItem().toString()=="BHD"){

            String convert= String.format("%.2f", amm*0.10*0.56);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CNY" & jComboBox2.getSelectedItem().toString()=="CAD"){

            String convert= String.format("%.2f", amm*0.34*0.56);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CNY" & jComboBox2.getSelectedItem().toString()=="CNY"){

            String convert= String.format("%.2f", amm);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CNY" & jComboBox2.getSelectedItem().toString()=="EGP"){

            String convert= String.format("%.2f", amm*4.28*0.56);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CNY" & jComboBox2.getSelectedItem().toString()=="EUR"){

            String convert= String.format("%.2f", amm*0.23*0.56);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CNY" & jComboBox2.getSelectedItem().toString()=="IDR"){

            String convert= String.format("%.2f", amm*3931.41*0.56);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CNY" & jComboBox2.getSelectedItem().toString()=="INR"){

            String convert= String.format("%.2f", amm*19.78*0.56);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CNY" & jComboBox2.getSelectedItem().toString()=="JPY"){

            String convert= String.format("%.2f", amm*29.71*0.56);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CNY" & jComboBox2.getSelectedItem().toString()=="KWD"){

            String convert= String.format("%.2f", amm*0.082*0.56);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CNY" & jComboBox2.getSelectedItem().toString()=="LKR"){

            String convert= String.format("%.2f", amm*54.03*0.56);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CNY" & jComboBox2.getSelectedItem().toString()=="MYR"){

            String convert= String.format("%.2f", amm*1.13*0.56);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CNY" & jComboBox2.getSelectedItem().toString()=="OMR"){

            String convert= String.format("%.2f", amm*0.10*0.56);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="CNY" & jComboBox2.getSelectedItem().toString()=="PKR"){

            String convert= String.format("%.2f", amm*42.16*0.56);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="CNY" & jComboBox2.getSelectedItem().toString()=="RUB"){

            String convert= String.format("%.2f", amm*20.77*0.56);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="CNY" & jComboBox2.getSelectedItem().toString()=="THB"){

            String convert= String.format("%.2f", amm*8.48*0.56);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="CNY" & jComboBox2.getSelectedItem().toString()=="USD"){

            String convert= String.format("%.2f", amm*0.27*0.56);
            jLabel1.setText(convert);
        }
//CNY is closed
        else if(jComboBox1.getSelectedItem().toString()=="EGP" & jComboBox2.getSelectedItem().toString()=="AED"){
            String convert= String.format("%.2f", amm*0.23);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EGP" & jComboBox2.getSelectedItem().toString()=="AUD"){

            String convert= String.format("%.2f", amm*0.36*0.23);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EGP" & jComboBox2.getSelectedItem().toString()=="BDT"){

            String convert= String.format("%.2f", amm*23.07*0.23);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EGP" & jComboBox2.getSelectedItem().toString()=="BHD"){

            String convert= String.format("%.2f", amm*0.10*0.23);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EGP" & jComboBox2.getSelectedItem().toString()=="CAD"){

            String convert= String.format("%.2f", amm*0.34*0.23);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EGP" & jComboBox2.getSelectedItem().toString()=="CNY"){

            String convert= String.format("%.2f", amm*1.78*0.23);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EGP" & jComboBox2.getSelectedItem().toString()=="EGP"){

            String convert= String.format("%.2f", amm);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EGP" & jComboBox2.getSelectedItem().toString()=="EUR"){

            String convert= String.format("%.2f", amm*0.23*0.23);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EGP" & jComboBox2.getSelectedItem().toString()=="IDR"){

            String convert= String.format("%.2f", amm*3931.41*0.23);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EGP" & jComboBox2.getSelectedItem().toString()=="INR"){

            String convert= String.format("%.2f", amm*19.78*0.23);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EGP" & jComboBox2.getSelectedItem().toString()=="JPY"){

            String convert= String.format("%.2f", amm*29.71*0.23);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EGP" & jComboBox2.getSelectedItem().toString()=="KWD"){

            String convert= String.format("%.2f", amm*0.082*0.23);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EGP" & jComboBox2.getSelectedItem().toString()=="LKR"){

            String convert= String.format("%.2f", amm*54.03*0.23);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EGP" & jComboBox2.getSelectedItem().toString()=="MYR"){

            String convert= String.format("%.2f", amm*1.13*0.23);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EGP" & jComboBox2.getSelectedItem().toString()=="OMR"){

            String convert= String.format("%.2f", amm*0.10*0.23);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EGP" & jComboBox2.getSelectedItem().toString()=="PKR"){

            String convert= String.format("%.2f", amm*42.16*0.23);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="EGP" & jComboBox2.getSelectedItem().toString()=="RUB"){

            String convert= String.format("%.2f", amm*20.77*0.23);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="EGP" & jComboBox2.getSelectedItem().toString()=="THB"){

            String convert= String.format("%.2f", amm*8.48*0.23);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="EGP" & jComboBox2.getSelectedItem().toString()=="USD"){

            String convert= String.format("%.2f", amm*0.27*0.23);
            jLabel1.setText(convert);
        }
//EGP is closed
        else if(jComboBox1.getSelectedItem().toString()=="EUR" & jComboBox2.getSelectedItem().toString()=="AED"){
            String convert= String.format("%.2f", amm*4.34);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EUR" & jComboBox2.getSelectedItem().toString()=="AUD"){

            String convert= String.format("%.2f", amm*0.36*4.34);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EUR" & jComboBox2.getSelectedItem().toString()=="BDT"){

            String convert= String.format("%.2f", amm*23.07*4.34);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EUR" & jComboBox2.getSelectedItem().toString()=="BHD"){

            String convert= String.format("%.2f", amm*0.10*4.34);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EUR" & jComboBox2.getSelectedItem().toString()=="CAD"){

            String convert= String.format("%.2f", amm*0.34*4.34);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EUR" & jComboBox2.getSelectedItem().toString()=="CNY"){

            String convert= String.format("%.2f", amm*1.78*4.34);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EUR" & jComboBox2.getSelectedItem().toString()=="EGP"){

            String convert= String.format("%.2f", amm*4.28*4.34);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EUR" & jComboBox2.getSelectedItem().toString()=="EUR"){

            String convert= String.format("%.2f", amm);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EUR" & jComboBox2.getSelectedItem().toString()=="IDR"){

            String convert= String.format("%.2f", amm*3931.41*4.34);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EUR" & jComboBox2.getSelectedItem().toString()=="INR"){

            String convert= String.format("%.2f", amm*19.78*4.34);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EUR" & jComboBox2.getSelectedItem().toString()=="JPY"){

            String convert= String.format("%.2f", amm*29.71*4.34);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EUR" & jComboBox2.getSelectedItem().toString()=="KWD"){

            String convert= String.format("%.2f", amm*0.082*4.34);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EUR" & jComboBox2.getSelectedItem().toString()=="LKR"){

            String convert= String.format("%.2f", amm*54.03*4.34);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EUR" & jComboBox2.getSelectedItem().toString()=="MYR"){

            String convert= String.format("%.2f", amm*1.13*4.34);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EUR" & jComboBox2.getSelectedItem().toString()=="OMR"){

            String convert= String.format("%.2f", amm*0.10*4.34);
            jLabel1.setText(convert);
        }
        else if(jComboBox1.getSelectedItem().toString()=="EUR" & jComboBox2.getSelectedItem().toString()=="PKR"){

            String convert= String.format("%.2f", amm*42.16*4.34);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="EUR" & jComboBox2.getSelectedItem().toString()=="RUB"){

            String convert= String.format("%.2f", amm*20.77*4.34);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="EUR" & jComboBox2.getSelectedItem().toString()=="THB"){

            String convert= String.format("%.2f", amm*8.48*4.34);
            jLabel1.setText(convert);
        }else if(jComboBox1.getSelectedItem().toString()=="EUR" & jComboBox2.getSelectedItem().toString()=="USD"){

            String convert= String.format("%.2f", amm*0.27*4.34);
            jLabel1.setText(convert);
        }


        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //Display jframe2
        try{
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtooHandler"+"C:\\Users\\User\\Documents\\NetBeansProjects\\CurrencyConvertor\\List of circulating currencies by state or territory.pdf");
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Check File details");
        }
       // NewJFrame1 jf1= new NewJFrame1();
        //jf1.show();//display jframe1

        //dispose();//close jframe
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        /*String p = "BDT";
        String q = "Rupee";
        String r="AED";
        String s= "EUR";
        String t= "OMR";
        String u= "PKR";
        String v= "USD" ;*/
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
